schema_version: 1

context:
  python_min: "3.12"
  version: "0.14.0"

package:
  name: growbikenet
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/growbikenet/growbikenet-${{ version }}.tar.gz
  sha256: c1a9f434ee1421d686549b01766903d1c4e643564a1459b08adb55106ca8650c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}
    - geopandas >=1
    - matplotlib-base
    - osmnx >=2
    - geojson
    - tqdm

tests:
  - python:
      imports:
        - growbikenet
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: BikeNetKit Python package to grow urban bicycle networks
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://bikenetkit.org/
  documentation: https://bikenetkit.github.io/GrowBikeNet/

extra:
  recipe-maintainers:
    - mszell
